app = "ccplant-worker-production"
primary_region = "nrt"

[build]
  image = "ghcr.io/ccplant/ccplant-api:v0.3.75"

[processes]
  worker = "worker"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"
